services:
  zoo1:
    image: zookeeper:3.8
    restart: always
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_CFG_EXTRA: "clientPort=2181"
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - zookeeper_net

  zoo2:
    image: zookeeper:3.8
    restart: always
    hostname: zoo2
    container_name: zoo2
    environment:
      ZOO_MY_ID: 2
      ZOO_PORT: 2181
      ZOO_CFG_EXTRA: "clientPort=2181"
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - zookeeper_net

  zoo3:
    image: zookeeper:3.8
    restart: always
    hostname: zoo3
    container_name: zoo3
    environment:
      ZOO_MY_ID: 3
      ZOO_PORT: 2181
      ZOO_CFG_EXTRA: "clientPort=2181"
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - zookeeper_net

  zoonavigator:
    image: elkozmon/zoonavigator:latest
    restart: always
    container_name: zoonavigator
    ports:
      - "9000:9000"
    environment:
      HTTP_PORT: 9000
    networks:
      - zookeeper_net

networks:
  zookeeper_net:
    driver: bridge
